# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan Fisk
email: ryanfisk2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! I'm Ryan Fisk, a passionate software developer specializing in full stack development and database management. With years of hands-on experience, I design and build robust applications that run smoothly across all layers of development, from backend logic to front-end user interfaces. My technical toolkit is filled with a variety of programming languages and frameworks, ensuring that I can adapt and excel in any development environment. I also bring a strong foundation in Agile methodologies and Scrum project management, enabling me to efficiently lead projects and collaborate effectively with teams. Dive into my portfolio to see how I transform complex challenges into seamless software solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryanfisk.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  RyanFisk6

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
